name: compass
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base
  - r-tidyverse
  - r-here
  - r-ggrepel
  - r-reshape2
  - r-ggtern
  - bioconductor-rtracklayer
  - loompy
  - numpy
  - pandas
  - varcode
  - pyensembl
  - pysam
  - pyvcf
  - samtools
  - bcftools
  - graphviz
  - mp3treesim
