name: numbat2
channels:
  - conda-forge
  - bioconda
dependencies:
  - cellsnp-lite
  - samtools
  - r-base
  - r-tidyverse
  - r-optparse
  - r-biocmanager
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-graph
  - bioconductor-rsamtools
